/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AiAssistant: typeof import("./components/AiAssistant.vue")["default"];
    TodoItem: typeof import("./components/TodoItem.vue")["default"];
    TodoList: typeof import("./components/TodoList.vue")["default"];
  }
}
